### ISSUE TITLE
Use poetry run for commands

### ISSUE THREAD

**Issue by felnne** [mapaction/rolling-data-scramble-dashboard-poc#51]
Currently we run the dashboard using:

```
$ cd rolling-data-scramble-dashboard-poc/
$ poetry shell
$ python3 app.py
```

This should change to use the [scripts](https://python-poetry.org/docs/cli/#run) option in `pyproject.toml`:

```toml
[tool.poetry.scripts]
update-dashboard = "mapaction_rds_dashboard:main"
```

```
$ cd rolling-data-scramble-dashboard-poc/
$ poetry run update-dashboard
```
